In [13]:
import numpy as np

In [14]:
data=np.array([[2100,   10,  800],
       [2500,   11,  850],
       [1800,   10,  760],
       [2000,   12,  800],
       [2300,   11,  810]])

In [19]:
import sklearn.preprocessing as pre

In [20]:
pre.scale(data)

array([[-0.16552118, -1.06904497, -0.1393466 ],
       [ 1.4896906 ,  0.26726124,  1.60248593],
       [-1.40693001, -1.06904497, -1.53281263],
       [-0.57932412,  1.60356745, -0.1393466 ],
       [ 0.66208471,  0.26726124,  0.2090199 ]])

In [21]:
pre.scale(data).mean(axis=0)

array([ 2.22044605e-17, -9.76996262e-16,  5.55111512e-18])

In [22]:
from sklearn.preprocessing import MinMaxScaler

In [23]:
arr=np.array([[ 1.2,  3.2],
       [-0.3, -1.2],
       [ 6.5, 10.1],
       [ 2.2, -8.4]])

In [24]:
default_scaler=MinMaxScaler()

In [25]:
default_scaler.fit_transform(arr)

array([[0.22058824, 0.62702703],
       [0.        , 0.38918919],
       [1.        , 1.        ],
       [0.36764706, 0.        ]])

In [27]:
costume_Scaler=MinMaxScaler(feature_range=(-10,10))

In [29]:
costume_Scaler.fit_transform(data)

array([[ -1.42857143, -10.        ,  -1.11111111],
       [ 10.        ,   0.        ,  10.        ],
       [-10.        , -10.        , -10.        ],
       [ -4.28571429,  10.        ,  -1.11111111],
       [  4.28571429,   0.        ,   1.11111111]])