In [1]:
import numpy as np

In [3]:
arr=np.array([-1,2,3,4],dtype=np.float32)

In [4]:
arr

array([-1.,  2.,  3.,  4.], dtype=float32)

In [5]:
 repr(arr)

'array([-1.,  2.,  3.,  4.], dtype=float32)'

In [6]:
np.array([np.nan,2,3,4])

array([nan,  2.,  3.,  4.])

In [7]:
arr2=arr.copy()

In [8]:
arr2


array([-1.,  2.,  3.,  4.], dtype=float32)

In [9]:
arr.dtype

dtype('float32')

In [10]:
arr2.astype(np.int32)


array([-1,  2,  3,  4], dtype=int32)

In [11]:


arr=np.arange(10)


In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
repr(arr)

'array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])'

In [14]:
np.arange(10,dtype="float32")

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [15]:
for i in np.arange(0,10):
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [16]:
for i in np.arange(0,10,2):
    print(i,end=" ")

0 2 4 6 8 

In [17]:
np.linspace(1,10) 

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [18]:
arr=np.arange(8)

In [19]:
rearr=np.reshape(arr,(2,4))


In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.ones_like(rearr)


array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:

like=np.zeros_like(rearr)

In [24]:
like.flatten()

array([0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
points=np.linspace(-3.5,1.5,101)


In [26]:
points


array([-3.5 , -3.45, -3.4 , -3.35, -3.3 , -3.25, -3.2 , -3.15, -3.1 ,
       -3.05, -3.  , -2.95, -2.9 , -2.85, -2.8 , -2.75, -2.7 , -2.65,
       -2.6 , -2.55, -2.5 , -2.45, -2.4 , -2.35, -2.3 , -2.25, -2.2 ,
       -2.15, -2.1 , -2.05, -2.  , -1.95, -1.9 , -1.85, -1.8 , -1.75,
       -1.7 , -1.65, -1.6 , -1.55, -1.5 , -1.45, -1.4 , -1.35, -1.3 ,
       -1.25, -1.2 , -1.15, -1.1 , -1.05, -1.  , -0.95, -0.9 , -0.85,
       -0.8 , -0.75, -0.7 , -0.65, -0.6 , -0.55, -0.5 , -0.45, -0.4 ,
       -0.35, -0.3 , -0.25, -0.2 , -0.15, -0.1 , -0.05,  0.  ,  0.05,
        0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,  0.45,  0.5 ,
        0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,  0.9 ,  0.95,
        1.  ,  1.05,  1.1 ,  1.15,  1.2 ,  1.25,  1.3 ,  1.35,  1.4 ,
        1.45,  1.5 ])

In [27]:
np.random.randint(5)

0

In [28]:
np.random.randint(0,100)

25

In [29]:
np.random.randint(0,100,(4,4))

array([[ 7, 55, 15, 63],
       [84, 83, 50, 33],
       [81,  5, 57, 78],
       [36,  8,  4, 27]])

In [30]:
np.random.uniform(0,10,(10,10))

array([[0.15924091, 4.73102716, 5.72408189, 9.08127409, 1.32096471,
        5.96477366, 3.68897887, 8.543029  , 9.25307811, 9.40859427],
       [9.83482526, 6.36056403, 8.1277274 , 5.25016456, 4.5612331 ,
        8.18953802, 2.74111888, 5.23594067, 5.70411484, 8.44708125],
       [5.30340152, 1.56506039, 3.44189065, 1.968864  , 2.32972222,
        3.80265265, 0.23739123, 0.69724381, 9.16338367, 6.32182324],
       [4.59407147, 4.45800159, 8.89159218, 1.09078402, 6.57903928,
        8.3357135 , 1.3436688 , 3.65489934, 2.59318244, 5.15445008],
       [1.89941158, 1.04287989, 1.26319184, 2.62980569, 7.4485728 ,
        7.68001069, 3.76004377, 8.37083642, 0.92261516, 0.59687219],
       [8.25817828, 4.20804904, 8.21781295, 4.07023387, 3.89965286,
        8.04474198, 6.52850187, 0.72658438, 7.70448138, 1.54368291],
       [3.63014669, 3.34611555, 3.60215536, 2.05533968, 2.14825885,
        6.42789396, 1.86266403, 3.51185076, 9.42102826, 4.91591232],
       [9.88717906, 5.32716581, 5.4642437

In [38]:
arr=np.array([1,2,3,4,1,2,3,4,12,34,4,342,3,2,334,])

In [34]:
arr[0]

1

In [35]:

arr=np.array([[6,10],[10,20]])

In [36]:
print(arr[0])


[ 6 10]


In [64]:
np.argmax(arr)

7

In [89]:
arr = np.array([[1,2,3],[4,5,6]])


In [90]:
np.argmax(arr,axis=1)

array([2, 2])

In [88]:
np.argmax(arr[[0,1]])

5

In [94]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])

In [96]:
arr.flatten()

array([-2, -1, -3,  4,  5, -6, -3,  9,  1])

In [115]:
arr = np.array([[1, 3, 54],
                [4, 5, 21],
                [6, 9, 1]])
print(repr(np.argmax(arr,axis=1)))

array([2, 2, 1])


In [116]:
print(repr(np.argmin(arr, axis=0)))

array([0, 0, 2])


In [5]:
np.where([True,False,True,False])

(array([0, 2]),)

In [6]:
arr=np.array([0,3,5,3,1])

In [9]:
np.where(arr==3)

(array([1, 3]),)